config/routes.rb
Rails.application.routes.draw do
  resources :policies
  resources :master_roles
  resources :colleges
  resources :departments
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/master_role.rb
class MasterRole < ApplicationRecord
end

app/controllers/master_roles_controller.rb
class MasterRolesController < ApplicationController
  before_action :set_master_role, only: [:show, :edit, :update, :destroy]

  # GET /master_roles
  # GET /master_roles.json
  def index
    @master_roles = MasterRole.all
  end

  # GET /master_roles/1
  # GET /master_roles/1.json
  def show
  end

  # GET /master_roles/new
  def new
    @master_role = MasterRole.new
  end

  # GET /master_roles/1/edit
  def edit
  end

  # POST /master_roles
  # POST /master_roles.json
  def create
    @master_role = MasterRole.new(master_role_params)

    respond_to do |format|
      if @master_role.save
        format.html { redirect_to @master_role, notice: 'Master role was successfully created.' }
        format.json { render :show, status: :created, location: @master_role }
      else
        format.html { render :new }
        format.json { render json: @master_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /master_roles/1
  # PATCH/PUT /master_roles/1.json
  def update
    respond_to do |format|
      if @master_role.update(master_role_params)
        format.html { redirect_to @master_role, notice: 'Master role was successfully updated.' }
        format.json { render :show, status: :ok, location: @master_role }
      else
        format.html { render :edit }
        format.json { render json: @master_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /master_roles/1
  # DELETE /master_roles/1.json
  def destroy
    @master_role.destroy
    respond_to do |format|
      format.html { redirect_to master_roles_url, notice: 'Master role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_master_role
      @master_role = MasterRole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def master_role_params
      params.require(:master_role).permit(:name, :context)
    end
end

app/helpers/master_roles_helper.rb
module MasterRolesHelper
end

app/views/master_roles/_form.html.erb
<%= form_with(model: master_role, local: true) do |form| %>
  <% if master_role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(master_role.errors.count, "error") %> prohibited this master_role from being saved:</h2>

      <ul>
      <% master_role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :master_role_name %>
  </div>

  <div class="field">
    <%= form.label :context %>
    <%= form.text_field :context, id: :master_role_context %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/master_roles/edit.html.erb
<h1>Editing Master Role</h1>

<%= render 'form', master_role: @master_role %>

<%= link_to 'Show', @master_role %> |
<%= link_to 'Back', master_roles_path %>

app/views/master_roles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Master Roles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Context</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @master_roles.each do |master_role| %>
      <tr>
        <td><%= master_role.name %></td>
        <td><%= master_role.context %></td>
        <td><%= link_to 'Show', master_role %></td>
        <td><%= link_to 'Edit', edit_master_role_path(master_role) %></td>
        <td><%= link_to 'Destroy', master_role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Master Role', new_master_role_path %>

app/views/master_roles/new.html.erb
<h1>New Master Role</h1>

<%= render 'form', master_role: @master_role %>

<%= link_to 'Back', master_roles_path %>

app/views/master_roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @master_role.name %>
</p>

<p>
  <strong>Context:</strong>
  <%= @master_role.context %>
</p>

<%= link_to 'Edit', edit_master_role_path(@master_role) %> |
<%= link_to 'Back', master_roles_path %>